baseurl = "https://markckeeley.com/"
languageCode = "en-us"
copyright = "Copyright &copy; 2015 - 2018 Mark Keeley All rights reserved."
title = "Mark Keeley"
author = "Mark Keeley"
canonifyurls = true
#Weird name but having this set to true fixes tag names
preserveTaxonomyNames = true
paginate = 10
theme = "mkminimal"

[taxonomies]
  tag = "tags"
  topic = "topics"

[params]
  #description = "my description"
# Shown in the home page
  subtitle = "Adding insult to injury since 1983"
  #brand = "Mark Keeley"
  dateFormat = "January 02, 2006"
  #showauthor = "true"
  #showtopics = "true"
  showtags = "true"

[permalinks]
  post = "/:year/:title/"

[menu]
  # Shown in the side menu.
  [[menu.main]]
    name = "Mark Keeley"
    pre = "<i class='fa fa-home fa-fw'></i>"
    weight = 0
    identifier = "home"
    url = "/"
  [[menu.main]]
    name = "Posts"
    pre = "<i class='fa fa-list fa-fw'></i>"
    weight = 1
    identifier = "post"
    url = "/post/"
  [[menu.main]]
    name = "Tags"
    pre = "<i class='fa fa-tag fa-fw'></i>"
    weight = 2
    identifier = "tag"
    url = "/tags/"
  [[menu.main]]
    name = "Projects"
    pre = "<i class='fa fa-book fa-fw'></i>"
    weight = 3
    identifier = "projects"
    url = "/pages/projects/"
  [[menu.main]]
    name = "Links"
    pre = "<i class='fa fa-link fa-fw'></i>"
    weight = 4
    identifier = "links"
    url = "/pages/links/"

