baseurl = "https://markkeeley.us"
languageCode = "en-us"
copyright = "Copyright &copy; 2015 - 2018 Mark Keeley"
title = "Mark Keeley"
author = "Mark Keeley"
canonifyurls = true
#Weird name but having this set to true fixes tag names
preserveTaxonomyNames = true
paginate = 10
theme = "mkminimal"

[taxonomies]
  tag = "tags"
  topic = "topics"

[params]
  #description = "my description"
# Shown in the home page
  subtitle = "Adding insult to injury since 1983"
  #brand = "Mark Keeley"
  dateFormat = "January 02, 2006"
  #showauthor = "true"
  #showtopics = "true"
  showtags = "true"

[permalinks]
  post = "/:year/:title/"
