baseurl = "http://markkeeley.us/"
languageCode = "en-us"
copyright = "Copyright &copy; 2015. All rights reserved."
title = "Mark Keeley"
author = "Mark Keeley"
canonifyurls = true
#Weird name but having this set to true fixes tag names
preserveTaxonomyNames = true
paginate = 7
theme = "simpleblue"

[taxonomies]
  tag = "tags"
  topic = "topics"

[params]
  #description = "my description"
# Shown in the home page
  subtitle = "Adding insult to injury since 1983"
  #brand = "Mark Keeley"
googleAnalytics = "UA-40744057-2"
# disqus = "Your Disqus shortname"
  dateFormat = "January 02, 2006"
  #highlightjs = "androidstudio"

[permalinks]
  post = "/:year/:title/"

[menu]
  # Shown in the side menu.
  [[menu.main]]
    name = "Mark Keeley"
    pre = "<i class='fa fa-home fa-fw'></i>"
    weight = 0
    identifier = "home"
    url = "/"
  [[menu.main]]
    name = "Posts"
    pre = "<i class='fa fa-list fa-fw'></i>"
    weight = 1
    identifier = "post"
    url = "/post/"
  [[menu.main]]
    name = "Tags"
    pre = "<i class='fa fa-tag fa-fw'></i>"
    weight = 2
    identifier = "tag"
    url = "/tags/"
  [[menu.main]]
    name = "Tutorials"
    pre = "<i class='fa fa-book fa-fw'></i>"
    weight = 3
    identifier = "tutorials"
    url = "/pages/tutorials/"
  [[menu.main]]
    name = "Links"
    pre = "<i class='fa fa-link fa-fw'></i>"
    weight = 4
    identifier = "links"
    url = "/pages/links/"

