baseurl = "https://markkeeley.us/"
languageCode = "en-us"
copyright = "Copyright &copy; 2015 - 2019 Mark Keeley"
title = "Mark Keeley"
author = "Mark Keeley"
canonifyurls = true
#Weird name but having this set to true fixes tag names
preserveTaxonomyNames = true
paginate = 10
theme = "mkminimal"

[taxonomies]
  tag = "tags"
  topic = "topics"

[params]
  #description = "my description"
# Shown in the home page
  subtitle = "Adding insult to injury since 1983"
  #brand = "Mark Keeley"
  dateFormat = "January 02, 2006"
  #showauthor = "true"
  #showtopics = "true"
  showtags = "true"

[permalinks]
  posts = "/:year/:title/"


[related]
# Only include matches with rank >= threshold. This is a normalized rank between 0 and 100.
threshold = 50
# To get stable "See also" sections we, by default, exclude newer related pages.
includeNewer = true
# Will lower case keywords in both queries and in the indexes.
toLower = true
[[related.indices]]
name = "keywords"
weight = 100
[[related.indices]]
name  = "author"
toLower = true
weight = 10
[[related.indices]]
name  = "tags"
weight = 100
[[related.indices]]
name  = "date"
weight = 10
pattern = "2006"
